[project]
org-name = "trackme"
name = "trackme-backend"
version = "1.0.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.8.0"

[[dependency]]
org = "ballerina"
name = "mongodb"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.8.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.3.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.5.0"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "1.5.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.5.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.3.0"

[[dependency]]
org = "ballerina"
name = "env"
version = "1.3.0"

[platform]
target = "java17" 