[package]
org = "adith"
name = "trackme"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.8.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.8.0"

[[dependency]]
org = "ballerina"
name = "observe"
version = "1.5.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.1.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.10.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.3.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.7.1"
