name: Frontend Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package*.json
    
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm ci
        else
          echo "No package.json found, skipping frontend tests"
          exit 0
        fi
    
    - name: Run linter
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm run lint
        else
          echo "No package.json found, skipping lint"
          exit 0
        fi
    
    - name: Run tests
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm test
        else
          echo "No package.json found, skipping tests"
          exit 0
        fi
    
    - name: Build application
      working-directory: ./frontend
      run: |
        if [ -f "package.json" ]; then
          npm run build
        else
          echo "No package.json found, skipping build"
          exit 0
        fi
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      if: hashFiles('frontend/package.json') != ''
      with:
        name: frontend-build
        path: frontend/.next/ 